tardis-sn/tardis

tardis/tests/test_atomic.py
Functional test for read_levels_data() in the atomic.py file
=> Test added in test_atomic.py

.travis.yml
=> added coverage back

tardis/data/tardis_config_definition.yml, tardis/io/config_reader.py, tardis/io/tests/test_config_reader.py, tardis/model.py
@unoebauer This should give you the ability to use the older yaml files
=> fixed the reader for the older Paper1 format yaml files

tardis/data/tardis_config_definition.yml, tardis/data/tardis_example_config.yml, tardis/io/config_reader.py, tardis/io/tests/data/tardis_configv1_ascii_density_abund.yml, tardis/io/tests/data/tardis_configv1_ascii_density_uniabund.yml, tardis/io/tests/data/tardis_configv1_uniform_density.yml, tardis/io/tests/test_config_reader.py, tardis/model.py
=> -fixed discrepancy concerning hold_iterations

conda-requirements
Just adding the update to conda-requirements to see if it works. Will add new plasma tests again after.
=> Added networkx to conda-requirements

tardis/plasma/tests/conftest.py, tardis/plasma/tests/test_property_atomic.py, tardis/plasma/tests/test_property_ion_population.py, tardis/plasma/tests/test_property_level_population.py
New test file test_property_level_population. Also added many more properties to conftest to simplify testing, and tidied up test_property_atomic and test_property_ion_population a little.
=> Added tests for plasma level population properties.

tardis/plasma/properties/property_collections.py, tardis/plasma/standard_plasmas.py
*Don't merge yet*
I expanded the stub for a property collection for the LTE Plasma but I'm not sure what I've done is the correct / ideal way to do it. Please look through and make suggestions if necessary.
=> Added LTE property collection.

tardis/plasma/tests/conftest.py, tardis/plasma/tests/test_partition_function.py
Just re-doing a cleaner version of this now that my last PR has been merged.
=> Updated tests for plasma partition function properties.

tardis/plasma/properties/radiative_properties.py, tardis/plasma/tests/conftest.py, tardis/plasma/tests/test_general_properties.py, tardis/plasma/tests/test_property_atomic.py, tardis/plasma/tests/test_property_ion_population.py, tardis/plasma/tests/test_property_level_population.py, tardis/plasma/tests/test_simple_plasma.py
This PR includes a test for the calculation of tau sobolev values. It also finishes off incomplete tests that were previously marked to be skipped, and updates some old tests to allow them to make use of the new pytest fixtures in conftest. I'm happy for this PR to be merged if it passes the Travis tests.
=> Finished plasma property tests for now.

tardis/data/tardis_config_definition.yml, tardis/io/config_reader.py, tardis/montecarlo/montecarlo.pyx, tardis/montecarlo/src/cmontecarlo.c, tardis/montecarlo/src/storage.h
Added possibility to emit virtual packets only in specified wavelength range
=> virtual packets frequency cut

tardis/data/tardis_config_definition.yml, tardis/model.py, tardis/plasma/properties/atomic.py, tardis/plasma/properties/ion_population.py, tardis/plasma/properties/level_population.py, tardis/plasma/properties/plasma_input.py, tardis/plasma/properties/property_collections.py, tardis/plasma/properties/radiative_properties.py, tardis/plasma/standard_plasmas.py, tardis/plasma/tests/conftest.py, tardis/plasma/tests/test_general_properties.py, tardis/plasma/tests/test_property_ion_population.py, tardis/plasma/tests/test_simple_plasma.py, tardis/plasma_array.py, tardis/tests/test_tardis_full.py
*Don't Merge*
I'm trying to replace the plasma_array file with the new legacy plasma in the model file, but I'm encountering an error related to the montecarlo stuff. It looks to me like one of the plasma properties is in the wrong format for the montecarlo part of the code, but I'm not sure which one or what the correct format should be. It might be the electron density property that I have just added that is causing this. I don't know much about the C part of Tardis so if anyone knows how to fix this that would be great. Here's the error:
@wkerzendorf
=> Work in progress: Replacing plasma_array with LegacyPlasma.

tardis/montecarlo/src/test_rpacket.c, tardis/montecarlo/tests/test_rpacket.py
@wkerzendorf take a look. I think its okay for merge.
=> [GSoC 2015 MRG] Testing getters setters

tardis/model.py, tardis/plasma/base.py, tardis/plasma/properties/atomic.py, tardis/plasma/properties/general.py, tardis/plasma/properties/ion_population.py, tardis/plasma/properties/level_population.py, tardis/plasma/properties/partition_function.py, tardis/plasma/properties/plasma_input.py, tardis/plasma/properties/property_collections.py, tardis/plasma/properties/radiative_properties.py, tardis/plasma/standard_plasmas.py, tardis/plasma/tests/conftest.py, tardis/plasma/tests/test_general_properties.py, tardis/plasma/tests/test_partition_function.py, tardis/plasma/tests/test_property_atomic.py, tardis/plasma/tests/test_property_ion_population.py, tardis/plasma/tests/test_property_level_population.py, tardis/plasma/tests/test_property_radiative.py, tardis/plasma/tests/test_simple_plasma.py
This works fine (I've compared the results from the new and old plasmas) but needs to be tidied up and have a few more properties added before merging.
Modules to change:
Modules to add:
Other tasks:
=> Added dilute-lte and nebular ionisation to the new plasma.

docs/physics/index.rst, docs/physics/plasma/index.rst
just a quick PR linking some of the older documentation about the plasma
=> linked the plasma documentation again

tardis/model.py, tardis/montecarlo/base.py, tardis/montecarlo/montecarlo.pyx, tardis/montecarlo/src/cmontecarlo.c, tardis/montecarlo/src/storage.h
We should close the other ones.
=> Rebasedvirtrunner

tardis/plasma/base.py, tardis/plasma/properties/general.py, tardis/plasma/properties/ion_population.py, tardis/plasma/properties/level_population.py, tardis/plasma/properties/partition_function.py, tardis/plasma/properties/radiative_properties.py
[Plasma_Graph.pdf](https://github.com/tardis-sn/tardis/files/1205/Plasma_Graph.pdf)
=> Added formulae to graph.

tardis/model.py
=> Fix of to_hdf5.

tardis/gui/widgets.py
=> Fix to plasma issue with GUI.

tardis/montecarlo/src/cmontecarlo.c
This PR changes cmontecarlo.c to use accessors to rpacket members exclusively.
=> changes to address issue #388

tardis/montecarlo/setup_package.py, tardis/montecarlo/src/cmontecarlo.c
Some more cleanups and a first stab at implementing better dependencies in the build system.
=> More cleanups

.travis.yml, tardis/atomic.py
This is a fix for #402 - but doesn't deal with all of them. Two of them I do not know how to get rid of.
=> fixes at least some of the pandas loc errors

tardis/atomic.py
This should fix #336. @orbitfold can you check
=> made sure that atomic does not reinsert the index into the dataframe

docs/physics/plasma/nlte.rst, tardis/atomic.py
Updated nlte.rst to change latex caligraph Rs to lower Rs
=> Updated nlte.rst

.travis.yml
=> updated the .travis.yml file to do a rehash before executing conda

tardis/montecarlo/src/cmontecarlo.c
=> calculate virtual spectrum independently of vpacket loggin - fixes #445

tardis/montecarlo/src/cmontecarlo.c
This ensures that the progress bar is most accurate.
=> Move progress bar update after calculation

.travis.yml, docs/workflow/pip-requirements, readthedocs.yml, tardis_ci/tardis_ci_env27.yml, tardis_ci/tardis_rtd_env27.yml
This restructures our TRAVIS runs slightly and mainly adds OSX build to test it working on macs.
=> Adding OSX to our travis build

.mailmap
@tardis-sn/tardis-core  can you guys have a quicklook and merge this - it will just allow us to compile commits from names and attribute them to a single person.
=> added mailmap to compile the commits for each person

README.rst, docs/index.rst
With this small PR, advertisement for participation in SOCIS 2016 is added
=> Add SOCIS 2016 advertisement

tardis/model.py
This is the final change before to_hdf is ready to be merged with master.
=> Use io.util.to_hdf to store the model

tardis/model.py, tardis/montecarlo/base.py, tardis/simulation/base.py
Moved Edotlu to the runner as per @wkerzendorf request. All tests pass locally.
=> Moved Edotlu to the runner

tardis/base.py, tardis/plasma/tests/conftest.py, tardis/tests/integration_tests/test_integration.py
This PR replaces the old `from_hdf5` method  with the new `from_hdf` method.
=> Change method name to `from_hdf`

docs/credits.rst
Another Mini-PR which updates the credits page of the documentation
=> Update SOCIS and GSOC students credits

docs/installation.rst
These are the new installation instructions as referenced in #707
=> Add new installation instructions

docs/gui.rst, docs/running.rst
This mini-PR just adds a warning into the documentation that the GUI is currently broken.
=> Add note about broken GUI to docu

tardis_env27.yml
Refere to https://github.com/sphinx-doc/sphinx/issues/3212
=> Fix clash in RTD dependencies

docs/notebooks/hdf_writer.ipynb, docs/to_hdf.rst
I have added a new notebook (`hdf_writer.ipynb`) , on how to use `HDFWriter` class.
I will update `to_hdf.ipynb` notebook , once all PR's regarding `TEP014` are merged.
=> [TEP014][DOC] HDFWriter Documentation

tardis/atomic.py, tardis/montecarlo/tests/test_formal_integral.py, tardis_env27.yml
@vg3095 that is for your work. will merge once it passes both linux and mac
=> Add new version to tardis_env27 and add pyne

tardis/plasma/properties/partition_function.py
A little change I forgot to make in the original PR.
=> LevelBoltzmannFactorNLTE.from_config is now a staticmethod

docs/running_tests.rst
It includes 
- Usage of `tardis-refdata` argument
- How to generate plasma reference file
=> [DOC] Update Running tests doc

.readthedocs.yml
to switch on using conda environment
=> add new readthedocs.yml 

tardis/gui/widgets.py
Whenever a GUI window is opened, LaTeX is force-deactivated in matplotlib. And... thanks to my vim setup, trailing whitespaces have been removed...
=> Force deactivate LaTeX in GUI - Fix #441

tardis/io/decay.py
=> Fix reference dictionary problem

tardis/montecarlo/base.py
This small PR fixes #760 and introduces a caching for ``spectrum_integrated``.
=> Add caching for integrated spectrum: Fix #760

.travis.yml, setup.cfg, setup.py, tardis/plasma/tests/test_plasma_dot_tex.py, tardis_env27.yml
I found today when trying to make a new TARDIS env that there were dependency issues. I've changed the dependencies slightly in the conda environment file.
=> fix dependencies for tardis conda env

tardis_env27.yml
=> trying to get travis to build

tardis/plasma/standard_plasmas.py
Fixes #835 
The delta_treatment was not enforced before.
=> Fixed indentation and position of delta_treatment in plasma/standard_plasmas.py

tardis/io/schemas/montecarlo.yml, tardis/io/tests/data/tardis_configv1_ascii_density_abund.yml, tardis/io/tests/data/tardis_configv1_ascii_density_uniabund.yml, tardis/io/tests/data/tardis_configv1_uniform_density.yml
This is a short fix for the schema file
=> Remove bbsampling from schema file

.travis.yml, tardis_env27.yml
=> Revert "change to new cython version"

setup.py
@unoebauer @chvogl can you please check
=> update the OPENMP text to be correct

docs/index.rst
@chvogl @unoebauer - that should be an easy merge
=> add atomic data description

docs/physics/plasma/plasma_plots/lte_ionization_balance.py, docs/physics/plasma/plasma_plots/nebular_ionization_balance.py, tardis/__init__.py, tardis/gui/widgets.py, tardis/io/atomic.py, tardis/io/model_reader.py, tardis/io/util.py, tardis/model/base.py, tardis/model/density.py, tardis/montecarlo/base.py, tardis/montecarlo/tests/test_formal_integral.py, tardis/plasma/properties/j_blues.py, tardis/plasma/standard_plasmas.py, tardis/tests/test_util.py, tardis/util/__init__.py, tardis/util/base.py, tardis/util/colored_logger.py
@chvogl as discussed
@unoebauer for your consideration
=> Refactor logging 

tardis/base.py
@chvogl @unoebauer for your consideration
=> Enabling the addition of callbacks in run_tardis

.travis.yml, ci-helpers/fetch_reference_data.sh, ci-helpers/install_miniconda.sh, ci-helpers/install_tardis_env.sh, tardis_env27.yml
=> Travis update2

docs/.nojekyll
This pull request is for adding the .nojekyll file in the master branch
1. The nojekll file has been added to the master branch and moved to the docs folder, as requested.
thank you
=> .nojekyll added to docs

.travis.yml
=> Autoupdate changelog

tardis/io/atomic.py, tardis/plasma/properties/partition_function.py
=> Revert "Fix nlte normalization "

azure-pipelines/doc-build.yml
Set prs to not trigger in line 6 of the documentation build yaml file for azure pipelines
=> Remove PR Trigger

azure-pipelines/doc-build.yml
=> Revert "Remove PR Trigger"

azure-pipelines/doc-build.yml
**Ready to merge**
This pr consists of two changes in the documentation build yaml file for the azure pipeline. 
Removing the trigger for pull requests by setting it to none.
Changing the input of installing the ssh-key task so that it accommodate multiple known hosts.
=> Update build documentation script

docs/workflow/azure_links.inc, docs/workflow/continuous_integration.rst, docs/workflow/git_links.inc
**This pull request is ready for meging, but it is a bad idea to do so.** I intend to accumulate and add everything I learn, as I set up more pipelines, before further updating the documentation. These are general improvements of the documentation from the new information I learn, as I continue to use azure pipelines.
Commit includes 2 files:
- **Modified** `docs/azure_links.inc:`
Added references to links specific to azure.
- **Modified** `docs/workflow/continuous_integration.rst:`
Added full information for known host info for installing ssh-key on azure.
Changed ssh-key install task format to accomdate the quick known host info method.
Added alternative default option for known host info.
Added general pipeline tutorial guide from azure.
Added null trigger option.
Added detailed matrix …
=> Update General CI Documentation

docs/models/examples/abund.dat, docs/models/examples/density.dat, tardis/io/schemas/base.yml
Fixed dumb base schema error.  csvy_model type should be string.  Symlinks fixed.
=> Base schema fix

tardis/io/atom_data/base.py
=> Raise error if requested atoms are not in the atomic data

docs/quickstart/quickstart.ipynb
Adding link for example configuration file.
=> Add links to Quickstart

docs/installation.rst
fix git clone rendering and add link to development guidelines in installation documentation
=> Fix installation documentation

tardis/__init__.py, tardis/analysis.py, tardis/data/vpacket_config.yml, tardis/gui/widgets.py, tardis/io/atom_data/atom_web_download.py, tardis/io/config_internal.py, tardis/io/model_reader.py, tardis/io/parsers/blondin_toymodel.py, tardis/io/parsers/stella.py, tardis/io/util.py, tardis/model/base.py, tardis/montecarlo/base.py, tardis/plasma/base.py, tardis/plasma/properties/ion_population.py, tardis/simulation/base.py, tardis/tests/integration_tests/conftest.py, tardis/tests/integration_tests/runner.py, tardis/tests/integration_tests/test_integration.py, tardis/util/base.py
@marxwillia @chvogl @ssim can you guys have a look
=> Large cleanup operation

.github/workflows/release.yml
This PR is for making automatic relases of TARDIS when a PR is merged to the master branch. 
Using GitHub Actions.
=> Automatic TARDIS releases

.orcid.csv
Added my orcid to the .orcid.csv file.
=> Added my orcid

tardis_env3.yml
Add `compilers` package from `conda-forge` channel.
=> Add `compilers` to environment YAML file

.zenodo.json
Updated Marc's ORCID information.
=> Updated zenodo.json

azure-pipelines/simple_test_framework.yml
Activate all TARDIS tests again.
Bug introduced in #995.
=> Re-activate TARDIS tests

.gitignore
It will be helpful for the users who use VSCode for developing (like me).
=> Git ignored VSCode specific files

azure-pipelines/simple_test_framework.yml
Reactivating codecov for TARDIS and Azure pipelines
=> CodeCov reintegration

.github/PULL_REQUEST_TEMPLATE.md
This adds a checkpoint to the PR template checklist, prompting the submitter of the PR to request/assign two reviewers to their PR.
This should help make sure that PRs get assigned reviewers.
n/a
=> Add checkpoint to PR template checklist

tardis_env3.yml
Change `astropy` required version from `tardis_env3.yml`
`astropy` was pinned **strictly** to v3.2.1 after accidentally merging #995.
All test pass.
=> Unpin astropy version

README.rst
- Replaced `coverage` badge with `codecov`.
- Update `zenodo` badge and bibtex citation.
- Moved badges to the top.
Badges should stay at the top of README.
Just check rendered README at PR tree.
=> Fix badges in README.rst

.orcid.csv
I'm adding my ORCID to the list that TARDIS references.
We'd like to make sure our ORCID list is up-to-date.
N/A (as far as I know!)
N/A
=> add arjun's name to the ORCID list

.git-blame-ignore-revs, README.rst
=> add git-blame-ignore for code style black Changes

docs/index.rst
=> Update index.rst to add mission statement

docs/index.rst
Change the formatting of the mission statement
=> Added better mission statement

docs/conf.py, docs/team.rst
An update to the governance model decided by TARDIS core
=> Update of the Governance model

docs/CODE_OF_CONDUCT.md, docs/team.rst
=> code of conduct symlink

tardis_env3.yml
Pin `pyne` momentarily until we can debug the segfault.
Linux testing pipeline on Azure is throwing segmentantion fault since `pyne` updated to v0.7.
=> Pin pyne to v0.5

tardis/montecarlo/montecarlo_numba/base.py
Instead of having `montecarlo_main_loop` reference the `montecarlo_configuration` module for `number_of_vpackets`, I explicitly pass `number_of_vpackets` as an argument to `montecarlo_main_loop` where it's called in `montecarlo_radial1d`. This ensures that the virtual spectrum isn't returned as all zeros.
When `montecarlo_main_loop` is first compiled, it "remembers" what the `number_of_vpackets` value is within the `montecarlo_configuration` module as it's first imported. However, we'd like to change `number_of_vpackets` from 0 to whatever the user input is on the last simulation iteration. Therefore, `number_of_vpackets` needs to be passed as an explicit argument to `montecarlo_main_loop` to ensure that the function recognizes the change in value.
I've checked "by hand" — see the below …
=> Fix numba_montecarlo virtual spectrum

tardis_env3.yml
=> Move to NumPy 1.19

tardis_env3.yml
=> Pin numpy to v1.19

docs/development/index.rst, docs/development/links.inc, docs/development/matterbridge.inc, docs/development/matterbridge.rst
Documentation about Mattermost bridges
=> Add Matterbridge documentation

tardis/montecarlo/base.py, tardis/montecarlo/montecarlo_numba/base.py, tardis/montecarlo/montecarlo_numba/interaction.py, tardis/montecarlo/montecarlo_numba/numba_config.py, tardis/montecarlo/montecarlo_numba/numba_interface.py, tardis/montecarlo/montecarlo_numba/r_packet.py, tardis/montecarlo/montecarlo_numba/single_packet_loop.py, tardis/montecarlo/montecarlo_numba/vpacket.py
=> Numba montecarlo profile1

docs/development/continuous_integration.rst
=> Update CI doc section 

docs/index.rst
Fixing a mistake in PR #1371.
After renaming a file in PR #1371, `docs/index.rst` was not updated, and therefore `docs/physics/plasma.rst` does not show up in the main TOC. This change fixes it.
I opened an issue for this-- #1377 .
I did test this, and plasma does appear in the sidebar.
=> Adding Plasma File in TOC

docs/conf.py
Changed the code for the `sphinx` package so as to accommodate update of date automatically which was previously hardcoded as a static value. 
- Added functionality for automatic date updation in docs  
Solved  #1401
Built the documentation through `sphinx` locally to test the changes. Looks good to me here:smile: 
Ran on `tardis` env created through `tardis3_env.yml`
=> added functionality for automatic date updation in docs

tardis/plasma/tests/test_complete_plasmas.py, tardis/simulation/tests/test_simulation.py, tardis/tests/test_tardis_full.py
applied `black` to tests fixed in #1399
I forgot to rebase before merging #1398 
Just ran locally
=> blackify tests

docs/development/azure_links.inc, docs/development/continuous_integration.rst, docs/development/git_links.inc
Just small changes to docs (missing links, etc.).
=> fixes for ci docs

.github/workflows/documentation-build.yml
=> enable manual trigger for docs

docs/using/interaction/physical_quantities.ipynb
Fixes the broken documentation build.
After the merge of #1562 the documentation did not build properly.
Successfully built docs can be found [here](https://smithis7.github.io/tardis/branch/patch-1/index.html).
**Checklist**
=> Fixing docs build problem

docs/using/visualization/generating_widgets.ipynb
=> Revert "Adding Instructions For Enabling `virtual_packet_logging` Properties in Config"

docs/quickstart/quickstart.ipynb
This PR updates the quickstart notebook according to #1477. 
**Examples**
**Checklist**
=> Changed Quickstart Example according to #1477

docs/conf.py, tardis_env3.yml
Removed:
- `beautifulsoup4` - unused
- `lxml` - unused
- `docopt` - unused
- `graphviz` - redundant, pulled by `pygraphviz`
- `notebook`- redundant, pulled by `jupyter`
Unpinned
- `pytest`
- `parso` (`jedi` updated and fixed)
- `sphinxcontrib-bibtex` (fixed by `conf.py`)
Moved:
- `matplotlib` - to Visualization/Widgets section
- `pygraphviz` - to Plasma
- `sphinx-jsonschema` - from `pip` to Documentation
Other:
- `dot2tex` already ported to Python 3  (remove d `Naereen` repo source) **NOT TESTED YET!**
- Add references (issues and PRs) to relevant pins
- Minor changes
Keep the environment file healthy.
**Examples**
**Checklist**
=> review environment file

.github/workflows/update-changelog.yml
Adding token at checkout step according to [this post](https://github.community/t/how-to-push-to-protected-branches-in-a-github-action/16101/35).
Trying to fix the changelog workflow (again)
Can't be tested until merged (sharing secrets on PRs is not possible).
**Examples**
**Checklist**
=> add token at checkout step

azure-pipelines/update-refdata.yml
Fix required by #1565.
**Examples**
**Checklist**
=> push montecarlo data to refdata repo

docs/development/update_refdata.rst
FINALLY updated the procedure to update the reference data according to the new automated workflow.
See: https://epassaro.github.io/tardis/branch/update-refdata-docs/development/update_refdata.html
Documentation was too old.
**Examples**
**Checklist**
=> update refdata procedure docs

docs/credits.rst, docs/sponsors.rst
- Adds descriptions of what each sponsor does for us into the sponsors page
- Acknowledges GitHub and NUMFocus on the credits page
Documentation built locally.
**Examples**
Here are the two relevant pages:
https://smithis7.github.io/tardis/branch/sponsor_description_doc/sponsors.html
https://smithis7.github.io/tardis/branch/sponsor_description_doc/credits.html
**Checklist**
=> Editing sponsors and credits pages of documentation

.git-blame-ignore-revs
-
See: https://akrabat.com/ignoring-revisions-with-git-blame/
**Examples**
**Checklist**
=> add latest black commit to .git-blame-ignore-revs

azure-pipelines/release-version.yml
:warning: should be merged before next sunday
As you can see [here](https://dev.azure.com/tardis-sn/TARDIS/_build/results?buildId=4772&view=logs&j=8d802004-fbbb-5f17-b73e-f23de0c1dec8&t=204a5865-46cc-58e7-fb50-496d953a770d) the steps "Check latest..." and "Check new..." show how the new tag will be resolved by the pipeline. In this example, latest tag was `2021.7.1` and a new tag (made today, July 2nd) is resolved `2021.7.2.0`. The trailing zero means this is the first release of that day (we missed that on our first release but it's ok).
The format of the tag will be `release-2021.7.2.0` while the release title will be `TARDIS v2021.7.2.0` in GitHub and Zenodo.
Finish the release cycle with CalVer.
**Examples** …
=> final changes for release pipeline

README.rst
VSCode can now open remote repositories . I'm adding a badge.
I think it might make it easy for pipelines
Not yet. 
**Checklist**
=> Open in VSCode badge

.mailmap
Title says it all 
**Examples**
**Checklist**
=> Add Jaladh to mailmap

docs/quickstart/quickstart.ipynb
Fixes documentation build after #1730.
See docs build: https://smithis7.github.io/tardis/branch/patch-1/quickstart/quickstart.html
**Checklist**
=> Fixing Docs Build

docs/news.rst
The JS used to customizing the Twitter Widget was causing the main page to slow down in FireFox. This fixes that. 
Earlier I was using the  `DOMSubtreeModified` `EventListener` to customize the widget when the "Load More Tweets" button was pressed. It worked but it called the `customizeTweetMedia` function way more times than necessary and that was causing the page to freeze. I am still don't know the page froze more severly in FireFox than in Chrome or Brave.
This uses a Mutation Observer to call the `customizeTweetMedia` function when more tweets have been added to the widget.
Fixes #1717 
**Examples**
Please visit the documentation [here](https://atharva-2001.github.io/tardis/branch/twitter_feed_fix/)
**Type of …
=> Fix for Unresponsive Main Page due to Twitter Widget

tardis/io/tests/test_configuration_namespace.py
This PR adds fixtures to `test_configuration_namespace.py`.
**Examples**
**Checklist**
=> Refactor `test_configuration_namespace.py`

tardis/montecarlo/montecarlo_numba/calculate_distances.py, tardis/montecarlo/montecarlo_numba/r_packet.py
when the MC crashes with diff nu < 0
=> printing packet information

.github/workflows/black-check.yml, tardis/__init__.py, tardis/analysis/opacities.py, tardis/gui/tests/test_gui.py, tardis/montecarlo/base.py, tardis/visualization/tools/sdec_plot.py, tardis_env3.yml
Changes to dependencies:
- `python` -> 3.8 (3.9 requires upgrading `pandas`, discuss)
- `astropy` -> 4 (v3 requires `python`<=3.7, v5 is also available, should we try?)
- `pickle5` -> removed (protocol v5 is available in `python>=3.8` , backporting is not required anymore)
- `jupyter` -> changed to `notebook` (no Qt deps required)
- `matplotlib` -> changed to `matplotlib-base` (no Qt deps required)
- `pyside2`/`pyqt` -> removed (if you want to use the Qt GUI install it manually, add procedure to docs)
- `Jinja=3.0.3` -> removed (bug fixed upstream)
- `docutils=0.16` -> removed (bug fixed upstream)
- `dot2tex` -> remove from `pip` section, use the `conda-forge` version (requires `python>=3.8)
- `black` -> 22.3 (Fix #1940, see also #1946)
Changes to code:
- Fix testing …
=> Update TARDIS environment after replacing PyNE

.azure-pipelines/compare-refdata.yml, .ci-helpers/download_reference_data.sh, .github/workflows/tests.yml
Oops.
Downloading HDF5 files from Azure mirror of the reference data through HTTPS.
:fire:
**Examples**
**Checklist**
=> Use Azure mirror for reference data in testing pipeline

docs/installation.rst
Added a note in "Environment update" section in installation docs on how to compare environment against env file. This is useful for checking if it needs update.
=> Added documetation on how to compare environment before update

.azure-pipelines/compare-refdata.yml, .azure-pipelines/templates/default.yml, .azure-pipelines/update-refdata.yml, .github/workflows/build-docs.yml, .github/workflows/clean-docs.yml, .github/workflows/codestyle.yml, .github/workflows/mailmap.yml, .github/workflows/post-release.yml, .github/workflows/pre-release.yml, GOVERNANCE.md
Fixed broken links in the workflow files and governance.md
Manual
=> Fix broken links in workflow files and goverance md

tardis/model/base.py
**Type:** :rocket: `restructure`
Removing old model state and renaming new model state.
=> Cleaning model state

docs/io/visualization/montecarlo_packet_visualization.ipynb
**Type:** :beetle: `bugfix` | :memo: `documentation`
Fix documentation pipeline.
=> Add missing cell to download atom data

.github/workflows/pre-release.yml
Changed the version of the failing part of the action since @v1 doesn't seem to exist any more.
=> Possible fix for prerelease workflow

tardis/io/tests/test_model_reader.py
=> Fixing test_store_runner_to_hdf

.github/workflows/post-release.yml, .github/workflows/pre-release.yml
**Type:** :beetle: `bugfix` |  :roller_coaster: `infrastructure`
- Use the `gh` CLI to approve the pull request
- Use a new token `INFRASTRUCTURE_COORDINATOR_TOKEN` for first approval
- Add a second approval with `CORE_COORDINATOR_TOKEN`
Closes #2157
Tested on a special repository:  https://github.com/epassaro/pr-automerge/pull/6
=> Fix for automerge

.mailmap, tardis/tests/test_tardis_full_formal_integral.py
**Type:** :vertical_traffic_light: `testing`
Changed the name of the class from `TestRunnerSimpleFormalInegral` to `TestRunnerSimpleFormalIntegral`
=> Fix typos in repository

tardis/util/base.py
=> add deprecated decorator

.github/workflows/benchmarks.yml
**Type:** :beetle: `bugfix` :vertical_traffic_light: `testing`  :roller_coaster: `infrastructure`
Changes the trigger to benchmarks workflow and corrects the step used for caching atom data workflow.
=> Benchmarks Comments and Atom Data Cache BugFix

tardis/plasma/properties/nlte_rate_equation_solver.py
Adds verbosity to NLTE rate equation solver assertion check.
=> Add verbose assert to NLTE rate equation

docs/installation.rst
=> update the lock file link in doc

.github/workflows/update-refdata.yml
Attempts to fix the currently failing tests.
https://github.com/tardis-sn/tardis/actions/runs/8787402380/job/24139534728
=> Modify Update Refdata to Push Regression Data Changes

.github/workflows/build-docs.yml
Updating the docs to use local atomic data
=> Updating the docs to use local atomic data

.github/workflows/tests.yml
**Type:**  :vertical_traffic_light: `testing`
The generation tests add a huge chunk of time to the test workflow. We'd want the test workflow to finish earlier. 
=> Edit Generation Tests

docs/index.rst, docs/io/hdf/index.rst
> Added the HDF documentation with two main sections: the overview and the extraction of the data in the H5 files.
@wkerzendorf 
@andrewfullard
@atharva-2001
=> Added HDF documentation.

.ruff.toml, pyproject.toml
Cherry picks commits from https://github.com/tardis-sn/tardis/pull/2626/commits  that update the ruff config.
=> Update Ruff Config

docs/_templates/layout.html
**Type:** :rocket: `feature` 
This PR aims at adding google analytics to tardis documentation.
=> Adding analytics to tardis documentation

docs/installation.rst
=> Updating "Environment update" section in tardis docs

benchmarks/benchmark_base.py, benchmarks/transport_montecarlo_interaction.py, benchmarks/transport_montecarlo_numba_interface.py, benchmarks/transport_montecarlo_packet.py, benchmarks/transport_montecarlo_vpacket.py
This PR aims at fixing some bugs which are causing the benchmarks workflow to fail.
=> Fix benchmarks errors

.github/workflows/pre-release.yml
Fixes env creation in pre release workflow
Env creation works, should work in the next weeks release.
https://github.com/tardis-sn/tardis/actions/runs/9936393057/job/27444518933?pr=2703
=> Pre Release Fix

README.rst
**Type:** :beetle: `bugfix`  | :roller_coaster: `infrastructure`
https://github.com/atharva-2001/tardis/tree/docstr-cov-badge-fix 
=> Fix Failing docstr-cov Badge

.github/workflows/tests.yml
**Type:** :beetle: `bugfix`  | :vertical_traffic_light: `testing` | :roller_coaster: `infrastructure`
This will combine codecov reports from our parallel setup and will give accurate coverage reports. This will also fix the failing `token not found` issue in the test pre-release pull request- https://github.com/tardis-sn/tardis/pull/2741
=> Fix Codecov

.github/workflows/codestyle.yml
**Type:** :beetle: `bugfix` | :biohazard: `breaking change` | :vertical_traffic_light: `testing`  | :roller_coaster: `infrastructure`
Fixes the ruff workflow.
Fixed workflow-https://github.com/tardis-sn/tardis/actions/runs/10142446576/job/28041767690?pr=2754
The action failed because of secrets, I temporarily changed the trigger to `pull_request` from `pull_request_target` for testing which caused it to fail. The workflow should work once merged.
=> Ruff Workflow Fix

.github/workflows/codestyle.yml
Sorry about the last fixes which did not work. I tested this one on my fork and it should work correctly now. 
https://github.com/atharva-2001/tardis/pull/50
https://github.com/atharva-2001/tardis/actions/runs/10266032468/job/28403500380
.
=> Ruff Fix 2

benchmarks/opacities_opacity.py, benchmarks/transport_montecarlo_packet_trackers.py
- Change parameters in benchmarks
- Resolves #2777 
=> Change parameters in benchmarks

tardis/simulation/tests/test_simulation.py
**Type:** :beetle: `bugfix` | :vertical_traffic_light: `testing` 
Files are saved here-
https://github.com/tardis-sn/tardis-regression-data/pull/18
=> Simulation Regression Tests

README.rst, README_TEMPLATE.rst
Fixing doc str coverage in read me file with the basic github badge.
=> Update badge for doc string coverage

.github/workflows/lfs-cache.yml
**Type:**  :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :roller_coaster: `infrastructure`
https://github.com/tardis-sn/tardis-regression-data/pull/43
=> Trigger LFS-cache generation from regression data repository

.github/workflows/compare-regdata.yml, docs/contributing/development/continuous_integration.rst
=> Document `LFS-cache` workflow and the `setup-lfs` action

.github/workflows/compare-regdata.yml, .github/workflows/labels-check.yml, .github/workflows/lfs-cache.yml, .github/workflows/util.yml
=> Workflow Label Pipeline and Fixes

.github/workflows/clean-docs.yml, .github/workflows/util.yml
=> BugFix: Utility workflow and Clean Docs workflow

benchmarks/transport_montecarlo_main_loop.py, tardis/conftest.py, tardis/transport/montecarlo/montecarlo_main_loop.py, tardis/visualization/tools/convergence_plot.py, tardis/workflows/standard_tardis_workflow.py
=> Progress Bar Fixes

tardis/visualization/tools/rpacket_plot.py, tardis/visualization/tools/tests/test_rpacket_plot.py
This PR aims at refactoring rpacket_plotter class
=> Cleanup rpacket plotter class

tardis/io/model/parse_composition_configuration.py, tardis/io/model/parse_density_configuration.py, tardis/io/model/readers/artis.py
=> Build docs issues fixes

tardis/visualization/plot_util.py, tardis/visualization/tests/test_plot_util.py, tardis/visualization/tools/liv_plot.py, tardis/visualization/tools/sdec_plot.py, tardis/visualization/tools/tests/test_sdec_plot.py
This PR aims at refactoring the sdec and liv plot classes
https://github.com/tardis-sn/tardis-regression-data/pull/47
=> Cleanup sdec and liv plotter classes

.mailmap, README.rst, README_TEMPLATE.rst
Fixes #3080
@andrewfullard is this the right place where I'm supposed to add the link? Should I add it in the README template file as well?
Kindly review this PR when you are free. Thanks.
=> add benchmarks link to readme

tardis/data/atomic_data_repo.yml
=> Correct atomic data path and checksum

.github/workflows/tests.yml, tardis/__init__.py, tardis/io/tests/test_HDFWriter.py, tardis/io/util.py
Closes #3073  and https://github.com/tardis-sn/tardis/issues/3117
<details>
<summary>Minimal Example</summary>
```py
from tardis.io.util import HDFWriterMixin
from tardis import __version__
import pandas as pd
import h5py
class TestHDF(HDFWriterMixin):
hdf_properties = ["value"]
def __init__(self, value):
self.value = value
obj = TestHDF(42.0)
obj.to_hdf("test.h5", path="data", overwrite=True)
with h5py.File("test.h5", 'r') as f:
def print_structure(name, obj):
if isinstance(obj, h5py.Dataset):
print(f"Dataset: {name} = {obj[()]}")
else:
print(f"Group: {name}")
f.visititems(print_structure)
print("\nReading …
```
=> Fix `tardis.__version__` and version to HDF metadata

.github/workflows/compare-regdata.yml, .mailmap
**Type:**  :vertical_traffic_light: `testing` | :roller_coaster: `infrastructure`
- Add checkout step for tardisbase repository
- Add steps to copy comparison files from tardisbase to tardis-regression-data
Below PR should me merged first for workflow to run properly
Reference PR: https://github.com/tardis-sn/tardisbase/pull/4
=> Update workflow to use comparison tools from tardisbase repository

tardis/visualization/plot_util.py, tardis/visualization/tests/test_plot_util.py, tardis/visualization/tools/liv_plot.py, tardis/visualization/tools/sdec_plot.py
This PR aims at fixing the issue regarding sdec plotter colors and remove the encoding of species in sdec plotter class.
Fixes:
https://github.com/tardis-sn/tardis/issues/3106
https://github.com/tardis-sn/tardis/issues/3071
=> Remove SDEC encoding and fix colors

README.rst, docs/tardis.bib
Updated the README.rst.
Also added the reference to Radioactivedecay package.
=> Updated readme

README.rst
Fixes the old reference to Pyne
=> Revise dependencies in README

pyproject.toml
=> Update Python to 3.13 in `pyproject.toml`

.github/workflows/tests.yml, tardis/conftest.py, tardis/visualization/tools/liv_plot.py, tardis/visualization/tools/sdec_plot.py, tardis/visualization/tools/tests/test_liv_plot.py, tardis/visualization/tools/tests/test_sdec_plot.py
Tests the `from_workflow` method in the SDEC plot and the liv plot using the existing regression data.
=> Viz modules `from_workflow` tests

.github/workflows/post-release.yml
Removes path that was left from the zenodo job I removed
=> Post Release Fix 
